version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: dgate-backend
      MONGO_INITDB_ROOT_PASSWORD: abd/zaro
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: